from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from orchestrator.app_workflow import orchestration_engine

app = FastAPI(title="Agentic AI Intelligent Loan Approval Gateway")

class LoanApplicationSchema(BaseModel):
    applicant_id: str = Field(..., example="APP-9012")
    age: int = Field(..., example=34)
    income: float = Field(..., example=75000.0)
    employment_type: str = Field(..., example="Salaried")
    credit_score: int = Field(..., example=780)
    loan_amount: float = Field(..., example=250000.0)
    existing_liabilities: float = Field(..., example=12000.0)
    location: str = Field(..., example="New York")

@app.post("/api/v1/evaluate-loan")
async def evaluate_loan(application: LoanApplicationSchema):
    try:
        initial_state = {"input_data": application.dict()}
        # Invoke the LangGraph Orchestrator Execution Pipeline
        final_state = orchestration_engine.invoke(initial_state)
        
        # This structure matches what your Streamlit UI expects
        return {
            "status": "Success",
            "decision": final_state.get("decision_synthesis", {}),
            "compliance_and_audit": final_state.get("compliance_audit", {}),
            "agent_logs": {
                "profile_agent_summary": final_state.get("profile_analysis", "No log generated by Profile Agent."),
                "risk_agent_summary": final_state.get("risk_analysis", "No log generated by Risk Agent.")
            }
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    # Enforcing Port 8001 alignment
    uvicorn.run(app, host="127.0.0.1", port=8001)